FROM dougley/wildbeast-env:latest
MAINTAINER hello@dougley.com

RUN mkdir -p /usr/src/WildBeast
WORKDIR /usr/src/WildBeast

COPY . /usr/src/WildBeast

RUN npm install

RUN npm run-script dbcreate

ENV BOT_ISBOT=true BOT_TOKEN=token BOT_EMAIL=email BOT_PASSWORD=password BOT_OAUTH=oauth \
    DATABASE_HOST=localhost DATABASE_PORT=28015 DATABASE_PASSWORD= DATABASE_USER=admin \
    SETTINGS_PREFIX=++ SETTINGS_AUTODELETEMSG=true SETTINGS_DELETE_TIMEOUT=3000 SETTINGS_DELETE_TIMEOUT_LONG=6000 SETTINGS_MAXVCSLOTS=10 \
    PERMISSIONS_MASTER= PERMISSIONS_LEVEL1= PERMISSIONS_LEVEL2= PERMISSIONS_LEVEL3= \
    API_KEYS_IMGFLIP_USERNAME=username API_KEYS_IMGFLIP_PASSWORD=password API_KEYS_GOOGLE=google API_KEYS_MASHAPE=mashape API_KEYS_TWITCH_ID=twitch

RUN chmod 755 ./entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh" ]
