packages:
  - apps/*
  - packages/*

engineStrict: true

allowBuilds:
  '@sentry/node-cpu-profiler': true
  '@sentry/node-native-stacktrace': true
  core-js: true
  core-js-pure: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
